name: Run Tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
  schedule:
    - cron: '0 7 * * 3'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.2, 8.1]
        laravel: ['11.*', '10.*']
        stability: [highest, lowest]
        database:
          - connection: sqlite

          # See: https://en.wikipedia.org/wiki/MySQL#Release_history
          - connection: mysql
            version: '8.4'
          - connection: mysql
            version: '8.0'

          # See: https://mariadb.org/about/#maintenance-policy
          - connection: mariadb
            version: '11.4'
          - connection: mariadb
            version: '10.11'
          - connection: mariadb
            version: '10.6'
          - connection: mariadb
            version: '10.5'

          # See: https://www.postgresql.org/support/versioning/
          - connection: pgsql
            version: 16
          - connection: pgsql
            version: 15
          - connection: pgsql
            version: 14
          - connection: pgsql
            version: 13
          - connection: pgsql
            version: 12
        exclude:
          - laravel: 11.*
            php: 8.1

    services:
      mysql:
        image: ${{ matrix.database.connection == 'mysql' && format('mysql:{0}', matrix.database.version) || '' }}
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mariadb:
        image: ${{ matrix.database.connection == 'mariadb' && format('mariadb:{0}', matrix.database.version) || '' }}
        env:
          MARIADB_DATABASE: test
          MARIADB_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mariadb-admin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: ${{ matrix.database.connection == 'pgsql' && format('postgres:{0}', matrix.database.version) || '' }}
        env:
          POSTGRES_DB: test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: "P${{ matrix.php }} - L${{ matrix.laravel }} - S: ${{ matrix.stability }} | ${{ matrix.database.connection }} ${{ matrix.database.version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Setup Laravel version
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.stability }}

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: ${{ matrix.database.connection }}
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: password
